### ISSUE TITLE
Display Disqus in Product Tab

### ISSUE THREAD

**Issue by raliabdillah** [firstred/mdproductsdisqus#1]
This module works great and displayed at the product page footer (displayFooterProduct hook),it will be great if it have an options to display it in product tab after product comments module

**Comment by firstred** [comment]
https://github.com/firstred/mdproductsdisqus/releases/tag/1.1.0

**Comment by raliabdillah** [comment]
Works Great at PS 1.6.1.6
I created an issue as recommendation for next version
