### ISSUE TITLE
Disqus Tab Placement.

### ISSUE THREAD

**Issue by raliabdillah** [firstred/mdproductsdisqus#2]
I have implement v1.1.0 at my customer site: www.widodaren.com with few adjustments:
1. Unhook mdDisqusFooter
2. Transplant mdDisqus in displayProductTab
3. Transplant mdDisqus in displayProductTabContent

Here, it works, but Disquss displayed in every tab.... then these steps:
4. in Tab.tpl line #19:
I Change this code: `<a href="#disqusTab" class="idTabHrefShort">{l s='Comments' mod='mdproductsdisqus'}</a></li>`  
To this: `<li><a href="#disqusTab" data-toggle="tab">{l s='Discuss' mod='mdproductsdisqus'}</a></li>` 
5. in TabContent.tpl line #19:
I Change this code: `<div id="disqusTab">` 
To this: `<div id="disqusTab" class="tab-pane page-product-box">` 

Now, my disquss tab works great.
If you guys think this is a good solution, I hope it can be done "automatically" when install the next version.

Regards
[Tab.zip](https://github.com/firstred/mdproductsdisqus/files/372882/Tab.zip)

**Comment by firstred** [comment]
Thanks for the suggestion, but we are not accepting theme specific requests. This module does not target a specific theme, except the default one. If the module does not fit in your theme, you should provide the theme specific files yourself. You can do that in the folder `/themes/<theme name>/`. Just look at the already existing theme files and you'll have an idea of how it's done.

Of course you can also pick your favorite hooks. This is part of the default workflow when working with PrestaShop as well. The hooks used will not change with module updates.
