### ISSUE TITLE
Comments counter

### ISSUE THREAD

**Issue by kunizza** [firstred/mdproductsdisqus#3]
Can't figure yet how to add a comments counter. Maybe it can be added after the tab name? ("#disqusTab")

**Comment by firstred** [comment]
I don't see any reason to implement this, to be honest. There's a comment counter in the disqus widget itself.

**Comment by firstred** [comment]
You can create a custom tpl for your theme and follow the instructions given by disqus. That should work.

**Comment by kunizza** [comment]
I've got it. Thank you.
Maybe there is the way to make an alerts about new comments in back office?

2016-08-01 14:46 GMT+03:00 Michael Dekker <notifications@github.com>:

**Comment by firstred** [comment]
For that you should use the disqus notification system
